// simply-daemon/admin/src/components/chat/ChatInput.svelte
<script lang="ts">
  import { chatStore } from '../../lib/stores/chat.svelte';

  let text = $state('');
  let textarea: HTMLTextAreaElement;

  async function send() {
    const msg = text.trim();
    if (!msg) return;
    text = '';
    // Reset height
    if (textarea) textarea.style.height = 'auto';
    await chatStore.sendMessage(msg);
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  function autoResize() {
    if (!textarea) return;
    textarea.style.height = 'auto';
    textarea.style.height = Math.min(textarea.scrollHeight, 200) + 'px';
  }
</script>

<div class="border-t border-border px-4 py-3">
  <div class="flex gap-2 items-end">
    <textarea
      bind:this={textarea}
      bind:value={text}
      oninput={autoResize}
      onkeydown={handleKeydown}
      placeholder="Type a message… (Enter to send, Shift+Enter for newline)"
      rows="1"
      disabled={chatStore.isLoading}
      class="flex-1 bg-white/5 border border-border rounded-lg px-3 py-2 text-sm text-fg
             placeholder:text-muted/50 resize-none outline-none focus:border-accent/50
             disabled:opacity-50"
    ></textarea>
    <button
      onclick={send}
      disabled={chatStore.isLoading || !text.trim()}
      class="px-4 py-2 bg-accent text-bg text-sm font-medium rounded-lg
             hover:bg-accent/80 disabled:opacity-30 disabled:cursor-not-allowed shrink-0"
    >Send</button>
  </div>
</div>

// noema_ui/src/components/ChatInput.tsx
import { useState, useRef, useEffect } from "react";

interface ChatInputProps {
  onSend: (message: string) => void;
  disabled?: boolean;
}

export function ChatInput({ onSend, disabled = false }: ChatInputProps) {
  const [message, setMessage] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Auto-resize textarea
  useEffect(() => {
    const textarea = textareaRef.current;
    if (textarea) {
      textarea.style.height = "auto";
      textarea.style.height = `${Math.min(textarea.scrollHeight, 200)}px`;
    }
  }, [message]);

  const handleSubmit = () => {
    const trimmed = message.trim();
    if (trimmed && !disabled) {
      onSend(trimmed);
      setMessage("");
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="border-t border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-4">
      <div className="flex gap-3 items-end max-w-4xl mx-auto">
        <textarea
          ref={textareaRef}
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Type a message..."
          disabled={disabled}
          rows={1}
          className="flex-1 px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-2xl resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-500 disabled:opacity-50"
        />
        <button
          onClick={handleSubmit}
          disabled={disabled || !message.trim()}
          className="px-4 py-3 bg-blue-500 hover:bg-blue-600 disabled:bg-gray-300 disabled:cursor-not-allowed text-white rounded-2xl transition-colors"
        >
          <svg
            className="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
            />
          </svg>
        </button>
      </div>
    </div>
  );
}
