// simply-daemon/admin/src/components/chat/MessageBubble.svelte
<script lang="ts">
  import type { DisplayMessage } from '../../lib/stores/chat.svelte';
  import type { ResolvedContent } from '../../lib/generated/types';

  interface Props {
    message: DisplayMessage;
    streaming?: boolean;
  }
  let { message, streaming = false }: Props = $props();

  const isUser = $derived(message.role === 'user');
  const isAssistant = $derived(message.role === 'assistant');
</script>

<div class="flex {isUser ? 'justify-end' : 'justify-start'}">
  <div class="max-w-[80%] rounded-lg px-3 py-2 text-sm
              {isUser ? 'bg-accent/20 text-fg' : 'bg-white/5 text-fg'}
              {streaming ? 'border border-accent/30' : ''}">
    {#each message.content as block}
      {@render contentBlock(block)}
    {/each}
  </div>
</div>

{#snippet contentBlock(block: ResolvedContent)}
  {#if 'text' in block && block.type === 'text'}
    <div class="whitespace-pre-wrap break-words">{block.text}</div>
  {:else if 'type' in block && block.type === 'asset'}
    {#if block.mime_type?.startsWith('image/')}
      <img
        src="/api/blob/{block.blob_hash}"
        alt="asset"
        class="max-w-full rounded mt-1"
      />
    {:else}
      <div class="text-xs text-muted italic">Asset: {block.mime_type}</div>
    {/if}
  {:else if 'type' in block && block.type === 'tool_call'}
    <div class="text-xs mt-1 p-2 bg-black/20 rounded font-mono">
      <span class="text-accent">⚡ {block.name}</span>
      <pre class="text-muted/70 overflow-x-auto mt-1">{JSON.stringify(block.arguments, null, 2)}</pre>
    </div>
  {:else if 'type' in block && block.type === 'tool_result'}
    <div class="text-xs mt-1 p-2 bg-black/20 rounded font-mono">
      <span class="text-green-400">✓ Result</span>
      {#each block.content as rc}
        {#if 'text' in rc}
          <pre class="text-muted/70 overflow-x-auto mt-1">{rc.text}</pre>
        {/if}
      {/each}
    </div>
  {:else if 'type' in block && block.type === 'document'}
    <span class="inline-block px-2 py-0.5 bg-accent/10 text-accent text-xs rounded">
      📄 doc:{block.document_id}
    </span>
  {:else}
    <div class="text-xs text-muted italic">Unknown content type</div>
  {/if}
{/snippet}

// noema_ui/src/components/MessageBubble.tsx
import ReactMarkdown from "react-markdown";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import type { DisplayMessage, DisplayContent, DisplayToolResultContent } from "../types";
import { AudioPlayer } from "./AudioPlayer";

interface MessageBubbleProps {
  message: DisplayMessage;
}

function renderToolResultContent(content: DisplayToolResultContent): React.ReactNode {
  if ("text" in content) {
    return <span>{content.text}</span>;
  }
  if ("image" in content) {
    return (
      <img
        src={`data:${content.image.mimeType};base64,${content.image.data}`}
        alt="Tool result"
        className="max-w-full rounded"
      />
    );
  }
  if ("audio" in content) {
    return (
      <AudioPlayer data={content.audio.data} mimeType={content.audio.mimeType} />
    );
  }
  return null;
}

function ContentBlock({ block }: { block: DisplayContent }) {
  if ("text" in block) {
    return (
      <ReactMarkdown
        remarkPlugins={[remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
          code(props) {
            const { children, className } = props;
            const isInline = !className;
            return isInline ? (
              <code className="bg-gray-800 text-gray-100 px-1 py-0.5 rounded text-sm">
                {children}
              </code>
            ) : (
              <code className={className}>{children}</code>
            );
          },
          pre(props) {
            return (
              <pre className="bg-gray-900 text-gray-100 p-3 rounded-lg overflow-x-auto text-sm">
                {props.children}
              </pre>
            );
          },
        }}
      >
        {block.text}
      </ReactMarkdown>
    );
  }

  if ("image" in block) {
    return (
      <img
        src={`data:${block.image.mimeType};base64,${block.image.data}`}
        alt="Message attachment"
        className="max-w-full rounded-lg"
      />
    );
  }

  if ("audio" in block) {
    return (
      <AudioPlayer data={block.audio.data} mimeType={block.audio.mimeType} />
    );
  }

  if ("toolCall" in block) {
    return (
      <div className="bg-purple-100 dark:bg-purple-900 text-purple-800 dark:text-purple-200 px-3 py-2 rounded-lg text-sm">
        <span className="font-semibold">Tool Call:</span> {block.toolCall.name}
      </div>
    );
  }

  if ("toolResult" in block) {
    return (
      <div className="bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200 px-3 py-2 rounded-lg text-sm">
        <span className="font-semibold">Tool Result:</span>
        <div className="mt-1">
          {block.toolResult.content.map((content, i) => (
            <div key={i}>{renderToolResultContent(content)}</div>
          ))}
        </div>
      </div>
    );
  }

  return null;
}

export function MessageBubble({ message }: MessageBubbleProps) {
  const isUser = message.role === "user";
  const isSystem = message.role === "system";

  return (
    <div
      className={`flex ${isUser ? "justify-end" : "justify-start"} mb-4`}
    >
      <div
        className={`max-w-[80%] px-4 py-3 rounded-2xl ${
          isUser
            ? "bg-blue-500 text-white"
            : isSystem
            ? "bg-yellow-100 dark:bg-yellow-900 text-yellow-900 dark:text-yellow-100"
            : "bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-100"
        }`}
      >
        <div className="prose prose-sm dark:prose-invert max-w-none">
          {message.content.map((block, i) => (
            <ContentBlock key={i} block={block} />
          ))}
        </div>
      </div>
    </div>
  );
}
