// noema/ui/src/lib/SidePanel.svelte
<script lang="ts">
  import type { ConversationInfo } from '@simply/client';
  import type { ActivityId } from './ActivityBar.svelte';
  import ConversationsPanel from './ConversationsPanel.svelte';
  import DocumentsPanel from './DocumentsPanel.svelte';

  type Props = {
    active: ActivityId;
    conversations: ConversationInfo[];
    currentConversationId: string | null;
    onNewConversation: () => void;
    onSelectConversation: (id: string) => void;
    onRenameConversation: (id: string, name: string) => void;
    onDeleteConversation: (id: string) => void;
  };

  const props: Props = $props();
</script>

<div class="flex h-full w-64 flex-col border-r border-gray-700 bg-surface">
  {#if props.active === 'conversations'}
    <ConversationsPanel
      conversations={props.conversations}
      currentId={props.currentConversationId}
      onNew={props.onNewConversation}
      onSelect={props.onSelectConversation}
      onRename={props.onRenameConversation}
      onDelete={props.onDeleteConversation}
    />
  {:else}
    <DocumentsPanel />
  {/if}
</div>

// noema-ui/src/components/SidePanel.tsx
import type { ConversationInfo } from "../types";
import type { ActivityId } from "./ActivityBar";
import { ConversationsPanel } from "./panels/ConversationsPanel";
import { DocumentsPanel } from "./panels/DocumentsPanel";

interface SidePanelProps {
  activeActivity: ActivityId;
  conversations: ConversationInfo[];
  currentConversationId: string;
  onNewConversation: () => void;
  onSelectConversation: (id: string) => void;
  onDeleteConversation: (id: string) => void;
  onRenameConversation: (id: string, name: string) => void;
}

export function SidePanel({
  activeActivity,
  conversations,
  currentConversationId,
  onNewConversation,
  onSelectConversation,
  onDeleteConversation,
  onRenameConversation,
}: SidePanelProps) {
  return (
    <div className="w-64 bg-surface border-r border-gray-700 flex flex-col h-full">
      {activeActivity === "conversations" && (
        <ConversationsPanel
          conversations={conversations}
          currentConversationId={currentConversationId}
          onNewConversation={onNewConversation}
          onSelectConversation={onSelectConversation}
          onDeleteConversation={onDeleteConversation}
          onRenameConversation={onRenameConversation}
        />
      )}
      {activeActivity === "documents" && <DocumentsPanel />}
    </div>
  );
}
