// noema_ui/src/components/ChatInput.tsx
import { useState, useRef, useEffect } from "react";

interface ChatInputProps {
  onSend: (message: string) => void;
  disabled?: boolean;
}

export function ChatInput({ onSend, disabled = false }: ChatInputProps) {
  const [message, setMessage] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Auto-resize textarea
  useEffect(() => {
    const textarea = textareaRef.current;
    if (textarea) {
      textarea.style.height = "auto";
      textarea.style.height = `${Math.min(textarea.scrollHeight, 200)}px`;
    }
  }, [message]);

  const handleSubmit = () => {
    const trimmed = message.trim();
    if (trimmed && !disabled) {
      onSend(trimmed);
      setMessage("");
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="border-t border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-4">
      <div className="flex gap-3 items-end max-w-4xl mx-auto">
        <textarea
          ref={textareaRef}
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Type a message..."
          disabled={disabled}
          rows={1}
          className="flex-1 px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-2xl resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-500 disabled:opacity-50"
        />
        <button
          onClick={handleSubmit}
          disabled={disabled || !message.trim()}
          className="px-4 py-3 bg-blue-500 hover:bg-blue-600 disabled:bg-gray-300 disabled:cursor-not-allowed text-white rounded-2xl transition-colors"
        >
          <svg
            className="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
            />
          </svg>
        </button>
      </div>
    </div>
  );
}

// noema/ui/src/lib/ChatInput.svelte
<script lang="ts">
  type Props = {
    onSend: (text: string) => void;
    disabled?: boolean;
    isLoading?: boolean;
  };
  const { onSend, disabled = false, isLoading = false }: Props = $props();

  let text = $state('');
  let textareaEl: HTMLTextAreaElement | undefined = $state();

  function autoresize() {
    if (!textareaEl) return;
    textareaEl.style.height = 'auto';
    // Cap at ~10 lines so long drafts don't eat the chat area.
    textareaEl.style.height = Math.min(textareaEl.scrollHeight, 240) + 'px';
  }

  function send() {
    const trimmed = text.trim();
    if (!trimmed || disabled) return;
    onSend(trimmed);
    text = '';
    // Next tick — after Svelte applies the cleared value.
    queueMicrotask(autoresize);
  }

  function onKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }
</script>

<div class="border-t border-gray-700 bg-background p-4">
  <div class="flex gap-2">
    <textarea
      bind:this={textareaEl}
      bind:value={text}
      oninput={autoresize}
      onkeydown={onKeydown}
      rows="1"
      placeholder={disabled ? 'Select a conversation to start chatting' : 'Message…'}
      {disabled}
      class="flex-1 resize-none rounded-lg border border-gray-700 bg-surface px-3 py-2 text-foreground placeholder-muted focus:border-teal-500 focus:outline-none"
    ></textarea>
    <button
      onclick={send}
      disabled={disabled || !text.trim() || isLoading}
      class="self-end rounded-lg bg-teal-600 px-4 py-2 font-medium text-white transition-colors hover:bg-teal-700 disabled:cursor-not-allowed disabled:opacity-50"
    >
      {isLoading ? '…' : 'Send'}
    </button>
  </div>
</div>
