// noema_ui/src/components/McpSettings.tsx
import { useState, useEffect, useCallback } from "react";
import { open } from "@tauri-apps/plugin-shell";
import type { McpServerInfo, McpToolInfo, McpAuthType } from "../types";
import * as tauri from "../tauri";

interface McpSettingsProps {
  onClose: () => void;
}

export function McpSettings({ onClose }: McpSettingsProps) {
  const [servers, setServers] = useState<McpServerInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showAddForm, setShowAddForm] = useState(false);
  const [expandedServer, setExpandedServer] = useState<string | null>(null);
  const [serverTools, setServerTools] = useState<Record<string, McpToolInfo[]>>({});
  const [oauthPending, setOauthPending] = useState<string | null>(null);

  // Form state - simplified
  const [formName, setFormName] = useState("");
  const [formUrl, setFormUrl] = useState("");
  const [formAuthType, setFormAuthType] = useState<McpAuthType>("none");
  const [formToken, setFormToken] = useState("");

  const loadServers = useCallback(async () => {
    try {
      setLoading(true);
      const list = await tauri.listMcpServers();
      setServers(list);
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadServers();
  }, [loadServers]);

  // Listen for OAuth completion events from deep link handler
  useEffect(() => {
    const unlisteners: (() => void)[] = [];

    tauri.onOauthComplete((_serverId) => {
      // OAuth completed successfully via deep link
      setOauthPending(null);
      loadServers();
    }).then((unlisten) => unlisteners.push(unlisten));

    tauri.onOauthError((err) => {
      setError(`OAuth error: ${err}`);
      setOauthPending(null);
    }).then((unlisten) => unlisteners.push(unlisten));

    return () => {
      unlisteners.forEach((unlisten) => unlisten());
    };
  }, [loadServers]);

  // Generate a simple ID from the name
  const generateId = (name: string) => {
    return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  };

  const handleAddServer = async () => {
    try {
      setError(null);
      const id = generateId(formName);

      await tauri.addMcpServer({
        id,
        name: formName,
        url: formUrl,
        authType: formAuthType,
        token: formAuthType === "token" ? formToken : undefined,
        // For OAuth, we use .well-known discovery - no client credentials needed from user
        useWellKnown: formAuthType === "oauth" ? true : undefined,
      });

      // Reset form
      setFormName("");
      setFormUrl("");
      setFormAuthType("none");
      setFormToken("");
      setShowAddForm(false);

      await loadServers();
    } catch (err) {
      setError(String(err));
    }
  };

  const handleRemoveServer = async (serverId: string) => {
    try {
      setError(null);
      await tauri.removeMcpServer(serverId);
      await loadServers();
    } catch (err) {
      setError(String(err));
    }
  };

  const handleConnect = async (serverId: string) => {
    try {
      setError(null);
      await tauri.connectMcpServer(serverId);
      await loadServers();
    } catch (err) {
      setError(String(err));
    }
  };

  const handleDisconnect = async (serverId: string) => {
    try {
      setError(null);
      await tauri.disconnectMcpServer(serverId);
      setServerTools(prev => {
        const next = { ...prev };
        delete next[serverId];
        return next;
      });
      await loadServers();
    } catch (err) {
      setError(String(err));
    }
  };

  const handleTestConnection = async (serverId: string) => {
    try {
      setError(null);
      const toolCount = await tauri.testMcpServer(serverId);
      alert(`Connection successful! Found ${toolCount} tools.`);
    } catch (err) {
      setError(String(err));
    }
  };

  const handleStartOauth = async (serverId: string) => {
    try {
      setError(null);
      setOauthPending(serverId);
      const authUrl = await tauri.startMcpOauth(serverId);
      // Open the authorization URL in the default browser using Tauri shell
      await open(authUrl);
    } catch (err) {
      setError(String(err));
      setOauthPending(null);
    }
  };

  const handleCompleteOauth = async (code: string) => {
    if (!oauthPending) return;
    try {
      setError(null);
      await tauri.completeMcpOauth(oauthPending, code);
      setOauthPending(null);
      await loadServers();
    } catch (err) {
      setError(String(err));
    }
  };

  const handleExpandServer = async (serverId: string) => {
    if (expandedServer === serverId) {
      setExpandedServer(null);
      return;
    }

    setExpandedServer(serverId);
    const server = servers.find(s => s.id === serverId);
    if (server?.isConnected && !serverTools[serverId]) {
      try {
        const tools = await tauri.getMcpServerTools(serverId);
        setServerTools(prev => ({ ...prev, [serverId]: tools }));
      } catch (err) {
        setError(String(err));
      }
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-2xl max-h-[80vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between">
          <h2 className="text-xl font-semibold text-gray-800 dark:text-white">
            MCP Servers
          </h2>
          <button
            onClick={onClose}
            className="p-2 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Error banner */}
        {error && (
          <div className="px-6 py-2 bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200 text-sm">
            {error}
            <button onClick={() => setError(null)} className="ml-2 underline">dismiss</button>
          </div>
        )}

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {loading ? (
            <div className="text-center py-8 text-gray-500 dark:text-gray-400">
              Loading...
            </div>
          ) : (
            <>
              {/* Server list */}
              {servers.length === 0 ? (
                <p className="text-gray-500 dark:text-gray-400 text-center py-8">
                  No MCP servers configured. Add one to get started.
                </p>
              ) : (
                <ul className="space-y-3 mb-6">
                  {servers.map(server => (
                    <li key={server.id} className="border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
                      <div
                        className="p-4 cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-700"
                        onClick={() => handleExpandServer(server.id)}
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            {/* Connection status indicator */}
                            <div className={`w-3 h-3 rounded-full ${server.isConnected ? 'bg-green-500' : 'bg-gray-400'}`} />
                            <div>
                              <h3 className="font-medium text-gray-800 dark:text-white">
                                {server.name}
                              </h3>
                              <p className="text-sm text-gray-500 dark:text-gray-400">
                                {server.url}
                              </p>
                            </div>
                          </div>
                          <div className="flex items-center gap-2">
                            <span className="text-xs px-2 py-1 bg-gray-100 dark:bg-gray-700 rounded text-gray-600 dark:text-gray-300">
                              {server.authType}
                            </span>
                            {server.isConnected && (
                              <span className="text-xs text-gray-500 dark:text-gray-400">
                                {server.toolCount} tools
                              </span>
                            )}
                            <svg
                              className={`w-4 h-4 transition-transform ${expandedServer === server.id ? 'rotate-180' : ''}`}
                              fill="none"
                              stroke="currentColor"
                              viewBox="0 0 24 24"
                            >
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                            </svg>
                          </div>
                        </div>
                      </div>

                      {/* Expanded content */}
                      {expandedServer === server.id && (
                        <div className="px-4 pb-4 border-t border-gray-200 dark:border-gray-700 pt-3">
                          {/* Actions */}
                          <div className="flex gap-2 mb-3">
                            {server.needsOauthLogin ? (
                              <button
                                onClick={() => handleStartOauth(server.id)}
                                className="px-3 py-1.5 text-sm bg-blue-500 hover:bg-blue-600 text-white rounded"
                              >
                                Login with OAuth
                              </button>
                            ) : server.isConnected ? (
                              <button
                                onClick={() => handleDisconnect(server.id)}
                                className="px-3 py-1.5 text-sm bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-200 rounded"
                              >
                                Disconnect
                              </button>
                            ) : (
                              <button
                                onClick={() => handleConnect(server.id)}
                                className="px-3 py-1.5 text-sm bg-green-500 hover:bg-green-600 text-white rounded"
                              >
                                Connect
                              </button>
                            )}
                            <button
                              onClick={() => handleTestConnection(server.id)}
                              className="px-3 py-1.5 text-sm bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-200 rounded"
                            >
                              Test
                            </button>
                            <button
                              onClick={() => handleRemoveServer(server.id)}
                              className="px-3 py-1.5 text-sm bg-red-100 dark:bg-red-900 hover:bg-red-200 dark:hover:bg-red-800 text-red-700 dark:text-red-200 rounded"
                            >
                              Remove
                            </button>
                          </div>

                          {/* Tools list */}
                          {server.isConnected && serverTools[server.id] && (
                            <div>
                              <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                                Available Tools:
                              </h4>
                              <ul className="text-sm space-y-1">
                                {serverTools[server.id].map(tool => (
                                  <li key={tool.name} className="text-gray-600 dark:text-gray-400">
                                    <span className="font-mono">{tool.name}</span>
                                    {tool.description && (
                                      <span className="text-gray-500 dark:text-gray-500"> - {tool.description}</span>
                                    )}
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      )}
                    </li>
                  ))}
                </ul>
              )}

              {/* OAuth code entry */}
              {oauthPending && (
                <OAuthCodeEntry
                  serverId={oauthPending}
                  onSubmit={handleCompleteOauth}
                  onCancel={() => setOauthPending(null)}
                />
              )}

              {/* Add server form */}
              {showAddForm ? (
                <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                  <h3 className="font-medium text-gray-800 dark:text-white mb-4">Add MCP Server</h3>
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                        Name
                      </label>
                      <input
                        type="text"
                        value={formName}
                        onChange={e => setFormName(e.target.value)}
                        placeholder="My Server"
                        className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                        URL
                      </label>
                      <input
                        type="text"
                        value={formUrl}
                        onChange={e => setFormUrl(e.target.value)}
                        placeholder="https://mcp-server.example.com"
                        className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                        Authentication
                      </label>
                      <select
                        value={formAuthType}
                        onChange={e => setFormAuthType(e.target.value as McpAuthType)}
                        className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      >
                        <option value="none">None</option>
                        <option value="token">Bearer Token</option>
                        <option value="oauth">OAuth 2.0 (via .well-known)</option>
                      </select>
                    </div>

                    {formAuthType === "token" && (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                          Token
                        </label>
                        <input
                          type="password"
                          value={formToken}
                          onChange={e => setFormToken(e.target.value)}
                          placeholder="Your bearer token"
                          className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                        />
                      </div>
                    )}

                    {formAuthType === "oauth" && (
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        OAuth endpoints will be discovered automatically via .well-known.
                        You'll be prompted to login after adding the server.
                      </p>
                    )}

                    <div className="flex gap-2 pt-2">
                      <button
                        onClick={handleAddServer}
                        disabled={!formName || !formUrl}
                        className="px-4 py-2 bg-blue-500 hover:bg-blue-600 disabled:bg-gray-400 text-white rounded font-medium"
                      >
                        Add Server
                      </button>
                      <button
                        onClick={() => setShowAddForm(false)}
                        className="px-4 py-2 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-200 rounded"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                </div>
              ) : (
                <button
                  onClick={() => setShowAddForm(true)}
                  className="w-full py-3 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg text-gray-500 dark:text-gray-400 hover:border-blue-400 hover:text-blue-500 transition-colors"
                >
                  + Add MCP Server
                </button>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// Component for entering OAuth authorization code
function OAuthCodeEntry({
  onSubmit,
  onCancel,
}: {
  serverId: string;
  onSubmit: (code: string) => void;
  onCancel: () => void;
}) {
  const [code, setCode] = useState("");

  return (
    <div className="mb-6 p-4 border border-blue-200 dark:border-blue-800 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
      <h4 className="font-medium text-gray-800 dark:text-white mb-2">
        Waiting for OAuth Login
      </h4>
      <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
        A browser window should have opened for authentication.
        After authorizing, the app will automatically complete the login.
        If it doesn't work, you can paste the code manually:
      </p>
      <div className="flex gap-2">
        <input
          type="text"
          value={code}
          onChange={e => setCode(e.target.value)}
          placeholder="Paste authorization code"
          className="flex-1 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
        />
        <button
          onClick={() => onSubmit(code)}
          disabled={!code}
          className="px-4 py-2 bg-blue-500 hover:bg-blue-600 disabled:bg-gray-400 text-white rounded"
        >
          Submit
        </button>
        <button
          onClick={onCancel}
          className="px-4 py-2 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-200 rounded"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}

// simply-daemon/admin/src/components/McpSettings.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getTransport } from '../lib/transport';
  import { mcpApi, oAuthApi } from '../lib/generated/api';
  import type { McpServerInfo, McpTool } from '../lib/generated/types';

  const t = getTransport();
  const mcp = mcpApi(t);
  const oauth = oAuthApi(t);

  let servers = $state<McpServerInfo[]>([]);
  let selectedTools = $state<McpTool[]>([]);
  let selectedServerId = $state<string | null>(null);
  let error = $state<string | null>(null);
  let loading = $state(false);

  // Add server form
  let showAdd = $state(false);
  let addName = $state('');
  let addUrl = $state('');
  let addAuthType = $state('none');
  let addClientId = $state('');
  let addClientSecret = $state('');

  onMount(() => refresh());

  async function refresh() {
    loading = true;
    try {
      servers = await mcp.listMcpServers();
    } catch (e) {
      console.error('[mcp]', e);
      error = `${e}`;
    }
    loading = false;
  }

  async function addServer() {
    if (!addName.trim() || !addUrl.trim()) return;
    try {
      const clientId = addClientId.trim() || null;
      const clientSecret = addClientSecret.trim() || null;
      await mcp.addMcpServer({
        id: addName.toLowerCase().replace(/\s+/g, '-'),
        name: addName,
        url: addUrl,
        authType: addAuthType,
        authToken: null,
        clientId,
        clientSecret,
        scopes: null,
      });
      addName = '';
      addUrl = '';
      addAuthType = 'none';
      addClientId = '';
      addClientSecret = '';
      showAdd = false;
      await refresh();
    } catch (e) {
      console.error('[mcp] add failed:', e);
      error = `Add failed: ${e}`;
    }
  }

  async function removeServer(id: string) {
    if (!confirm(`Remove server "${servers.find(s => s.id === id)?.name || id}"?`)) return;
    try {
      await mcp.removeMcpServer(id);
      if (selectedServerId === id) { selectedServerId = null; selectedTools = []; }
      await refresh();
    } catch (e) {
      console.error('[mcp] remove failed:', e);
      error = `Remove failed: ${e}`;
    }
  }

  // No prefill needed — daemon stores OAuth credentials by URL in config

  async function connectServer(id: string) {
    try {
      await mcp.connectMcpServer(id);
      await refresh();
    } catch (e) {
      console.error('[mcp] connect failed:', e);
      error = `Connect failed: ${e}`;
    }
  }

  async function disconnectServer(id: string) {
    try {
      await mcp.disconnectMcpServer(id);
      await refresh();
    } catch (e) {
      console.error('[mcp] disconnect failed:', e);
      error = `Disconnect failed: ${e}`;
    }
  }

  async function startOauth(id: string) {
    try {
      const info = await oauth.startOauth(id);
      window.open(info.authUrl, '_blank');
      // Poll for completion
      const interval = setInterval(async () => {
        await refresh();
        const srv = servers.find(s => s.id === id);
        if (srv && !srv.needsOauthLogin) clearInterval(interval);
      }, 3000);
      setTimeout(() => clearInterval(interval), 120_000);
    } catch (e) {
      console.error('[mcp] oauth failed:', e);
      error = `OAuth failed: ${e}`;
    }
  }

  async function showTools(id: string) {
    if (selectedServerId === id) { selectedServerId = null; selectedTools = []; return; }
    try {
      selectedTools = await mcp.getMcpServerTools(id);
      selectedServerId = id;
    } catch (e) {
      console.error('[mcp] tools failed:', e);
      error = `Failed to load tools: ${e}`;
    }
  }

  function statusColor(s: McpServerInfo): string {
    if (s.isConnected) return 'text-green-400';
    if (s.status.startsWith('retrying')) return 'text-yellow-400';
    return 'text-muted/50';
  }

  function statusLabel(s: McpServerInfo): string {
    if (s.isConnected) return `connected (${s.toolCount} tools)`;
    if (s.needsOauthLogin) return 'needs OAuth login';
    return s.status;
  }
</script>

<div class="space-y-4">
  <div class="flex items-center justify-between">
    <h2 class="text-lg font-medium">MCP Servers</h2>
    <button
      class="text-xs px-3 py-1 rounded bg-accent/20 text-accent hover:bg-accent/30"
      onclick={() => showAdd = !showAdd}
    >{showAdd ? 'Cancel' : '+ Add Server'}</button>
  </div>

  {#if error}
    <div class="px-3 py-2 bg-red-900/30 text-red-300 text-xs rounded">
      {error}
      <button class="ml-2 underline" onclick={() => error = null}>dismiss</button>
    </div>
  {/if}

  {#if showAdd}
    <div class="border border-border rounded-lg p-4 space-y-3">
      <input
        class="w-full bg-white/5 border border-border rounded px-3 py-2 text-sm text-fg outline-none"
        placeholder="Server name"
        bind:value={addName}
      />
      <input
        class="w-full bg-white/5 border border-border rounded px-3 py-2 text-sm text-fg outline-none"
        placeholder="URL (e.g. https://mcp.example.com)"
        bind:value={addUrl}
      />
      <select
        class="w-full bg-white/5 border border-border rounded px-3 py-2 text-sm text-fg outline-none"
        bind:value={addAuthType}
      >
        <option value="none">No Auth</option>
        <option value="oauth">OAuth</option>
        <option value="bearer">Bearer Token</option>
      </select>
      {#if addAuthType === 'oauth'}
        <input
          class="w-full bg-white/5 border border-border rounded px-3 py-2 text-sm text-fg outline-none"
          placeholder="OAuth Client ID"
          bind:value={addClientId}
        />
        <input
          class="w-full bg-white/5 border border-border rounded px-3 py-2 text-sm text-fg outline-none"
          type="password"
          placeholder="OAuth Client Secret (optional)"
          bind:value={addClientSecret}
        />
      {/if}
      <button
        class="w-full px-4 py-2 bg-accent text-bg text-sm font-medium rounded hover:bg-accent/80"
        onclick={addServer}
      >Add Server</button>
    </div>
  {/if}

  {#if loading && servers.length === 0}
    <div class="text-sm text-muted">Loading...</div>
  {/if}

  <div class="space-y-2">
    {#each servers as srv}
      <div class="border border-border rounded-lg p-3">
        <div class="flex items-center gap-3">
          <div class="flex-1 min-w-0">
            <div class="text-sm font-medium truncate">{srv.name}</div>
            <div class="text-xs text-muted/50 truncate">{srv.url}</div>
            <div class="text-xs {statusColor(srv)} mt-0.5">{statusLabel(srv)}</div>
          </div>
          <div class="flex gap-1 shrink-0">
            {#if srv.needsOauthLogin}
              <button
                class="text-xs px-2 py-1 rounded bg-accent/20 text-accent hover:bg-accent/30"
                onclick={() => startOauth(srv.id)}
              >Login</button>
            {:else if srv.isConnected}
              <button
                class="text-xs px-2 py-1 rounded bg-white/5 text-muted hover:text-fg"
                onclick={() => showTools(srv.id)}
              >{selectedServerId === srv.id ? 'Hide' : 'Tools'}</button>
              {#if srv.authType === 'oauth'}
                <button
                  class="text-xs px-2 py-1 rounded bg-white/5 text-muted hover:text-fg"
                  onclick={() => startOauth(srv.id)}
                >Re-auth</button>
              {/if}
              <button
                class="text-xs px-2 py-1 rounded bg-white/5 text-muted hover:text-fg"
                onclick={() => disconnectServer(srv.id)}
              >Disconnect</button>
            {:else}
              <button
                class="text-xs px-2 py-1 rounded bg-accent/20 text-accent hover:bg-accent/30"
                onclick={() => connectServer(srv.id)}
              >Connect</button>
            {/if}
            <button
              class="text-xs px-2 py-1 rounded bg-red-900/20 text-red-400 hover:bg-red-900/40"
              onclick={() => removeServer(srv.id)}
            >Remove</button>
          </div>
        </div>

        {#if selectedServerId === srv.id && selectedTools.length > 0}
          <div class="mt-3 border-t border-border/50 pt-2">
            <div class="text-xs text-muted mb-1">Tools ({selectedTools.length})</div>
            <div class="grid gap-1">
              {#each selectedTools as tool}
                <div class="text-xs p-2 bg-black/20 rounded">
                  <span class="text-accent font-mono">{tool.name}</span>
                  {#if tool.description}
                    <span class="text-muted/70 ml-2">{tool.description}</span>
                  {/if}
                </div>
              {/each}
            </div>
          </div>
        {/if}
      </div>
    {:else}
      {#if !loading}
        <div class="text-sm text-muted/50 text-center py-4">No MCP servers configured</div>
      {/if}
    {/each}
  </div>
</div>
